[package]
name = "dorestic"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "*"
chrono = "*"
clap = { version = "*", features = ["derive"] }
crossterm = { version = "*", features = ["event-stream"] }
directories = "5"
flexi_logger = "*"
futures = { version = "*" }
humansize = "*"
log = "*"
nix = { version = "*", features = ["process"] }
ratatui = { version = "*", features = ["unstable-widget-ref"] }
rusqlite = { version = "*", features = ["functions", "trace"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
tokio = { version = "*", features = ["macros", "io-std", "io-util", "process", "rt-multi-thread", "rt"] }
tokio-util = { version = "*", features = ["codec"] }
uuid = { version = "*", features = ["v4"] }

[profile.release]
codegen-units = 1
lto = "fat"
