[package]
name = "dorestic"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "*"
chrono = "*"
clap = { version = "*", features = ["derive"] }
crossterm = "*"
directories = "5"
flexi_logger = "*"
humansize = "*"
indicatif = "*"
log = "*"
nix = { version = "*", features = ["process"] }
ratatui = { version = "*", features = ["unstable-widget-ref"] }
rusqlite = { version = "*", features = ["bundled", "functions", "trace"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
unicode-segmentation = "*"
uuid = { version = "*", features = ["v4"] }

[profile.release]
codegen-units = 1
lto = "fat"
