[package]
name = "dorestic"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "*"
chrono = "*"
clap = { version = "*", features = ["derive"] }
crossterm = "*"
directories = "5"
flexi_logger = "*"
humansize = "*"
indicatif = "*"
log = "*"
nix = { version = "*", features = ["process"] }
ratatui = { version = "*", features = ["unstable-widget-ref"] }
rusqlite = { version = "*", features = ["bundled", "functions", "trace"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
unicode-segmentation = "*"

[lib]
path = "src/lib.rs"

[[bin]]
name = "dorestic"
path = "src/main.rs"

[features]
bench = []

[profile.release]
codegen-units = 1
lto = "fat"

[dev-dependencies]
criterion = { version = "*", features = ["html_reports"] }
uuid = { version = "*", features = ["v4"] }

[[bench]]
name = "cache"
harness = false
