[package]
name = "dorestic"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "*"
clap = { version = "*", features = ["derive"] }
crossterm = { version = "*", features = ["event-stream"] }
directories = "5"
env_logger = "*"
futures = { version = "*" }
log = "*"
nix = { version = "*", features = ["process"] }
ratatui = { version = "*", features = ["unstable-widget-ref"] }
rusqlite = { version = "*", features = ["functions"] }
scopeguard = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
tokio = { version = "*", features = ["macros", "io-std", "io-util", "process", "rt-multi-thread", "rt"] }
tokio-util = { version = "*", features = ["codec"] }
