max_width = 80
match_arm_blocks = false
error_on_line_overflow = true
imports_granularity = "Module"
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
use_small_heuristics = "Max"
use_field_init_shorthand = true
